version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.8
    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            python3 -m venv rain
            python3 -m pip install --upgrade pip
            pip install -r requirements.txt
      - run:
          name: run tests
          command: ./test_handler.sh
      - run:
          name: run server
          command: ./run_server.sh